name: gymsafeflutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  persistent_bottom_nav_bar_v2: ^5.3.0
  swipe_cards: ^2.0.0+1
  dotted_border: ^2.1.0
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  user_repository:
    path: packages/user_repository
  flutter_dotenv: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

assets:
  - assets/
  - assets/icons/
