// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWgly3GVS4C1ax0KAXFQXxCyPGTmuCkzo',
    appId: '1:245871650724:web:03fbcd35f8eb8a266e0331',
    messagingSenderId: '245871650724',
    projectId: 'gymsafedatabase',
    authDomain: 'gymsafedatabase.firebaseapp.com',
    storageBucket: 'gymsafedatabase.appspot.com',
    measurementId: 'G-G4Y9BQKWB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwLLCq3inepnf3rcQNlip_rprPzscRfpM',
    appId: '1:245871650724:android:11d2b98935b0a9ef6e0331',
    messagingSenderId: '245871650724',
    projectId: 'gymsafedatabase',
    storageBucket: 'gymsafedatabase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW4N6a2RBsgCOlUiXx04Flr8SGDA912do',
    appId: '1:245871650724:ios:76ade64a26bc162c6e0331',
    messagingSenderId: '245871650724',
    projectId: 'gymsafedatabase',
    storageBucket: 'gymsafedatabase.appspot.com',
    iosBundleId: 'com.example.gymsafeflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW4N6a2RBsgCOlUiXx04Flr8SGDA912do',
    appId: '1:245871650724:ios:76ade64a26bc162c6e0331',
    messagingSenderId: '245871650724',
    projectId: 'gymsafedatabase',
    storageBucket: 'gymsafedatabase.appspot.com',
    iosBundleId: 'com.example.gymsafeflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWgly3GVS4C1ax0KAXFQXxCyPGTmuCkzo',
    appId: '1:245871650724:web:1533f9b6bd44a16c6e0331',
    messagingSenderId: '245871650724',
    projectId: 'gymsafedatabase',
    authDomain: 'gymsafedatabase.firebaseapp.com',
    storageBucket: 'gymsafedatabase.appspot.com',
    measurementId: 'G-QH8V1SGPE7',
  );

}